const englishValues = {
  'welcomeText': 'Invite your friends and plan your next trip!',
  'policiesText':
      'By planning your trip with plann.er you automatically agree to our ',
  'useTerms': 'terms of use',
  'and': ' and ',
  'privacyPolicies': 'privacy policies',
  'where': 'Where?',
  'when': 'When?',
  'continueT': 'Continue',
  'changePlaceDate': 'Change place/date',
  'toPrep': 'to',
  'ofPrep': 'of',
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'mayLong': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'november': 'November',
  'december': 'December',
  'jan': 'Jan.',
  'feb': 'Feb.',
  'mar': 'Mar.',
  'apr': 'Apr.',
  'may': 'May.',
  'jun': 'Jun.',
  'jul': 'Jul.',
  'aug': 'Aug.',
  'sep': 'Sep.',
  'oct': 'Oct.',
  'nov': 'Nov.',
  'dec': 'Dec.',
  'errorWhileLoadingCities': 'Error loading cities',
  'tryAgain': 'Try Again',
  'confirmTrip': 'Confirm Trip',
  'guestsHint': 'Who will be on the trip?',
  'invitedGuests': 'Invited person(s)',
  'selectedGuests': 'Select guests',
  'guestsText':
      'Guests will receive emails to confirm their participation in the trip.',
  'emailHint': 'Enter the guest\'s email',
  'inviteLabel': 'Invite',
};
