const portugueseValues = {
  'welcomeText': 'Convide seus amigos e planeje sua próxima viagem!',
  'policiesText':
      'Ao planejar sua viagem pela plann.er você automaticamente concorda com nossos ',
  'useTerms': 'termos de uso',
  'and': ' e ',
  'privacyPolicies': 'políticas de privacidade',
  'where': 'Para onde?',
  'when': 'Quando?',
  'continueT': 'Continuar',
  'changePlaceDate': 'Alterar local/data',
  'toPrep': 'a',
  'ofPrep': 'de',
  'january': 'Janeiro',
  'february': 'Fevereiro',
  'march': 'Março',
  'april': 'Abril',
  'mayLong': 'Maio',
  'june': 'Junho',
  'july': 'Julho',
  'august': 'Agosto',
  'september': 'Setembro',
  'octuber': 'Outubro',
  'november': 'Novembro',
  'december': 'Dezembro',
  'jan': 'Jan.',
  'feb': 'Fev.',
  'mar': 'Mar.',
  'apr': 'Abr.',
  'may': 'Mai.',
  'jun': 'Jun.',
  'jul': 'Jul.',
  'aug': 'Ago.',
  'sep': 'Set.',
  'oct': 'Out.',
  'nov': 'Nov.',
  'dec': 'Dez.',
  'errorWhileLoadingCities': 'Erro ao carregar cidades',
  'tryAgain': 'Tente Novamente',
  'confirmTrip': 'Confirmar Viagem',
  'guestsHint': 'Quem estará na viagem?',
  'invitedGuests': 'pessoa(s) convidada(s)',
  'selectedGuests': 'Selecionar convidados',
  'guestsText':
      'Os convidados irão receber e-mails para confirmar a participação na viagem.',
  'emailHint': 'Digite o e-mail do convidado',
  'inviteLabel': 'Convidar',
  'confirmLabel': 'Confirmar criação da viagem',
  'forConfirmTrip': 'Para concluir a criação da viagem para ',
  'inTheDatesOf': ' nas datas de ',
  'fillYourData': ' preencha seus dados abaixo:',
  'yourName': 'Seu nome',
  'yourEmail': 'Seu e-mail pessoal',
  'confirmTripButton': 'Confirmar criação da viagem',
  'sunday': 'Domingo',
  'monday': 'Segunda-feira',
  'tuesday': 'Terça-feira',
  'wednesday': 'Quarta-feira',
  'thursday': 'Quinta-feira',
  'friday': 'Sexta-feira',
  'saturday': 'Sábado',
  'activitiesLabel': 'Atividades',
  'newActivity': 'Nova Atividade',
};
