// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAphuXOjp7SCZgH7x2pcZnzgPJNW12ortA',
    appId: '1:567678381020:web:f9bbfe5bd06842bc0dfd19',
    messagingSenderId: '567678381020',
    projectId: 'planner-journey',
    authDomain: 'planner-journey.firebaseapp.com',
    storageBucket: 'planner-journey.firebasestorage.app',
    measurementId: 'G-4WB1B6YBTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvuN96CAz_hIaj-v7hNpBPu6LnayovBw',
    appId: '1:567678381020:android:8a48fa6e08d375e60dfd19',
    messagingSenderId: '567678381020',
    projectId: 'planner-journey',
    storageBucket: 'planner-journey.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAphuXOjp7SCZgH7x2pcZnzgPJNW12ortA',
    appId: '1:567678381020:web:c6837726b72e34330dfd19',
    messagingSenderId: '567678381020',
    projectId: 'planner-journey',
    authDomain: 'planner-journey.firebaseapp.com',
    storageBucket: 'planner-journey.firebasestorage.app',
    measurementId: 'G-0C51XKBRQL',
  );
}
